# Generated by Django 5.0.6 on 2024-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='cassinumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2001.2, max_digits=9),
        ),
    ]
