# Generated by Django 5.0.6 on 2024-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_carlist_cassinumber_carlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='cassinumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
