# Generated by Django 5.0.6 on 2024-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_carlist_cassinumber_alter_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locaiton', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
            ],
        ),
    ]
